name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci || true
      - name: Build
        run: npm run build
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist
